name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Q1
      id: q1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Q1
        setup-command: pip install numpy scikit-learn matplotlib pytest
        command: pytest test_AIstats_lab.py::test_generate_clean_data_shapes test_AIstats_lab.py::test_generate_clean_data_true_coefficient_range
          test_AIstats_lab.py::test_add_outliers_shapes_and_copy test_AIstats_lab.py::test_add_outliers_effect
          test_AIstats_lab.py::test_plot_dataset_with_outliers_returns_figure
        timeout: 10
        max-score: 5
    - name: Q2
      id: q2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Q2
        setup-command: pip install numpy scikit-learn matplotlib pytest
        command: pytest test_AIstats_lab.py::test_fit_model_coefficients_are_floats
          test_AIstats_lab.py::test_ordinary_linear_regression_is_badly_affected test_AIstats_lab.py::test_robust_models_improve_over_linear_regression
          test_AIstats_lab.py::test_coefficient_errors_dictionary test_AIstats_lab.py::test_best_robust_model
          test_AIstats_lab.py::test_ransac_detects_added_outliers test_AIstats_lab.py::test_plot_regression_fits_returns_figure
          test_AIstats_lab.py::test_plot_ransac_inliers_outliers_returns_figure
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        Q1_RESULTS: "${{steps.q1.outputs.result}}"
        Q2_RESULTS: "${{steps.q2.outputs.result}}"
      with:
        runners: q1,q2
